# Generated by Django 4.0.5 on 2022-06-30 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_rate_5_rate_ratenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='ratenum',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
